name: main-build

on:
  push:
    branches:
      - main

jobs:
  setup:
    if: ${{ !contains(github.event.head_commit.message, 'chore(release)') }}
    uses: ./.github/workflows/setup.yml

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Load yarn & node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-yarn-node-modules
        with:
          path: ./node_modules
          key: lock-${{ hashFiles('./yarn.lock') }}
      - name: Cache build output
        uses: actions/cache@v3
        env:
          cache-name: cache-build
        with:
          path: ./packages/*/dist
          key: packages-${{ hashFiles('./packages/**') }}
      - name: Build changed projects
        run: yarn lerna run --stream build

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Load yarn & node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-yarn-node-modules
        with:
          path: ./node_modules
          key: lock-${{ hashFiles('./yarn.lock') }}
      - name: Load build output
        uses: actions/cache@v3
        env:
          cache-name: cache-build
        with:
          path: ./packages/*/dist
          key: packages-${{ hashFiles('./packages/**') }}
      - name: Cache coverage output
        uses: actions/cache@v3
        env:
          cache-name: cache-coverage
        with:
          path: ./coverage/coverage-final.json
          key: coverage-${{ hashFiles('./packages/*/lib/**') }}
      - name: Run unit tests with coverage
        run: yarn run test:cov

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Load yarn & node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-yarn-node-modules
        with:
          path: ./node_modules
          key: lock-${{ hashFiles('./yarn.lock') }}
      - name: Load build output
        uses: actions/cache@v3
        env:
          cache-name: cache-build
        with:
          path: ./packages/*/dist
          key: packages-${{ hashFiles('./packages/**') }}
      - name: Run e2e tests
        run: yarn lerna run test:e2e --stream

  codecov:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v3
      - name: Load coverage output
        uses: actions/cache@v3
        env:
          cache-name: cache-coverage
        with:
          path: ./coverage/coverage-final.json
          key: coverage-${{ hashFiles('./packages/*/lib/**') }}
      - name: Upload report to codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/coverage-final.json
          flags: unittests

  npm-dev-release:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - e2e-tests
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Load yarn & node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-yarn-node-modules
        with:
          path: ./node_modules
          key: lock-${{ hashFiles('./yarn.lock') }}
      - name: Check for changes
        id: changed_packages
        run: echo "CHANGED_PACKAGES=$(yarn lerna changed -p | wc -l | xargs)" >> $GITHUB_OUTPUT
      - name: Load build output
        if: steps.changed_packages.outputs.CHANGED_PACKAGES != '0'
        uses: actions/cache@v3
        env:
          cache-name: cache-build
        with:
          path: ./packages/*/dist
          key: packages-${{ hashFiles('./packages/**') }}
      - name: Publish next version
        if: steps.changed_packages.outputs.CHANGED_PACKAGES != '0'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "access=public" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
          yarn lerna publish --preid dev --dist-tag dev -y
